services:
  - type: web
    name: retrievo-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    region: oregon
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: GEMINI_API_KEY
        sync: false
